# Generated by Django 6.0 on 2025-12-07 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('CRYPTO', 'Crypto'), ('FOREX', 'Forex'), ('STOCK', 'Stock'), ('INDICE', 'Indice'), ('SYNTHETIC', 'Synthetic')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('entry_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('size', models.DecimalField(decimal_places=10, max_digits=20)),
                ('stop_loss', models.DecimalField(decimal_places=10, max_digits=20)),
                ('take_profit', models.DecimalField(decimal_places=10, max_digits=20)),
                ('confidence_score', models.FloatField(help_text='AI Confidence Score (0-1)')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('pnl', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('deriv_contract_id', models.CharField(blank=True, max_length=50, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='core.asset')),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=10, max_digits=20)),
                ('high', models.DecimalField(decimal_places=10, max_digits=20)),
                ('low', models.DecimalField(decimal_places=10, max_digits=20)),
                ('close', models.DecimalField(decimal_places=10, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=4, default=0, max_digits=24)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.asset')),
            ],
            options={
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['asset', 'datetime'], name='core_priceh_asset_i_390030_idx')],
                'unique_together': {('asset', 'datetime')},
            },
        ),
    ]
