# Generated by Django 6.0 on 2025-12-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_trade_deriv_contract_id_asset_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='deriv_contract_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
