# Generated by Django 5.2.9 on 2025-12-18 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_wallettransaction_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_trade', models.BooleanField(default=False, help_text='Enable AI Auto-Trading')),
                ('min_confidence', models.FloatField(default=0.9, help_text='Minimum confidence score for auto-trading')),
                ('max_risk_per_trade', models.DecimalField(decimal_places=2, default=10.0, help_text='Max amount to risk per trade in USD', max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
